# Generated by Django 3.1 on 2020-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_follownotification_likenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='follownotification',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='likenotification',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
