# Generated by Django 3.1 on 2020-08-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_profile_isprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
    ]
